### PR TITLE
Resolved: run CI workflow only when code inside waspc/ changes

### LINKED ISSUE #291: Run Haskell CI worklow only when code inside waspc/ changes
Since have a monorepo and haskell compiler (waspc/) is not the only thing in the repo -> instead we also have `examples/`, and we have `web/`.
However, current github actions workflow, ci.yaml, runs on any change in the repo. This doesn't make much sense, especially if for example only stuff in `web/` changes -> we don't need to build `waspc/` in that case, instead we are just wasting time and resources.

We should find a way to run relevant CI logic based on which files changed.

I found https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/11 .
From this it sounds like we should probably create one workflow for waspc (we could rename ci.yaml to waspc-ci.yaml) and use `on.push.paths` to ensure it runs only for changes in `waspc/`, and then if needed we can create more workflows for handling other parts of the repo, e.g. we could create `web-ci.yaml` for `web/` and similar.

### PR DESCRIPTION
**Pull request by suyog-patil-21**
### Description

Fix Haskell CI workflow only when code inside waspc/ changes (Fixes #291).

### Select what type of change this PR introduces:

1. [ ] **Just code/docs improvement** (no functional change). 
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### CODE REVIEW

**Comment by infomiho** [comment]
@suyog-patil-21 do you know why did it run for this PR?

**Comment by suyog-patil-21** [comment]
As GitHub Action workflow was changed. this PR required a approval to run.
So on the Maintainers console there is a button  "Approve and Run". 
So When the Maintainer approved it that why this PR's WASPC-CI workflow. ran.

**Comment by suyog-patil-21** [comment]
I just noticed that this workflow will not work for on `pull_request` event. I will fix this. Please do not merge this PR.

**Comment by suyog-patil-21** [comment]
I have fix the on `pull_request` event. You can now merge this PR

**Comment by Martinsos** [comment]
@suyog-patil-21 looking good!
I wonder if we could easily test this. I will create two dummy PRs to see how this behaves.

**Review by Martinsos — APPROVED** [review]

**Comment by Martinsos** [comment]
Nice job @suyog-patil-21 , works good, merging!

**Pull request merged**
