### PR TITLE
App spec validation

### PR DESCRIPTION
**Pull request by Martinsos**
The motivation for this behaviour was validating certain properties of AppSpec before it goes into Generator, so that Generator can have easier time due to not having to worry about certain properties being enforced or not.

Validations that we currently care about are:
- AppSpec should have exactly one `app` declaration.
- If a Page has `authRequired` set, then `app.auth` also needs to be defined.
- Entity provided to `app.auth.userEntity` needs to have field `email` of type `string` and field `password` with type `string`.

Especially important is the first one, because many parts of the Generator use `app` and them having to check it every time for existence would be impractical.

In Haskell, we normally want to capture as much info as we can in the type system, so compiler helps us. Therefore, the best validation is the one that is supported by the type system! So, the ideal validation in Haskell is when the output of the validation logic ensures via the type system that it can't be invalid.

For example, for AppSpec and having exactly one `app`, that could be smth like:
 - `validateAppSpec :: AppSpec -> Either [ValidationError] ValidAppSpec`
 - `data AppSpec = { ... , app :: Maybe App, ... }`
 - `data ValidAppSpec = { ... , app :: App, ... }`

So, output type guarantees that AppSpec has exactly one type, and don't have to worry about it ever again! There is no way we forget to validate AppSpec -> if we didn't validate it, we wouldn't be able to obtain ValidAppSpec at all. So this means validation was done successfully, if we have ValidAppSpec, and those properties that were validated are now encoded in the structure itself. There is a nice blog post by Alexis King about this: https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/ .

So while that is ideal solution, I gave up on it relatively quickly, for the following reasons:
1. AppSpec is relatively complex and is also built from other structures (App, Page, Entity, ...). Duplicating all of these, or even a subset of them, would be a lot of work and would reduce our capability to make quick changes. Basically, we would be introducing a new intermediate representation (IR), and I felt that the cost of implementing and maintaining it is relatively high at this moment of time, compared to what we get. 
2. I wasn't assured that we will be able to catch all of the properties in the structure, at least not in the practical way. For example, the first one (1 `app`) is easy to catch in the structure. However, the second one (authRequired requiring app.auth) is already harder -> I think we could store the info about Pages that have authRequired into app.auth, and that way would ensure that property, but that would make it a bit impractical to deal with specific pages, since we would have to do lookup in the app.auth. Finally, the third one, with userEntity, I don't even have an idea how to encode that into the structure, at least not in any remotely practical fashion. And I am sure there will be more validation checks in the future.

Also, we need to note that this output structure (from validation) is still "mutable" -> not really mutable of course, we are in Haskell, but one function could make a copy of it with some part somewhat different, invalidate some the properties that way, but still propagate it to other functions, and again we don't have a guarantee that validated properties hold!

So just encoding stuff in the structure is not enough -> we also need to ensure that copies of structure that are invalid can't be created on the fly. We could ensure this by hiding field accessors for its records and exposing only getters (validation function would be the only one with access to actual accessors so it can perform construction).

So taking those two into account, that is really a lot of work.

Therefore, I concluded I could avoid replicating the structure and introducing new IR, if I would instead somehow "mark" it as validated. It would not be as elegant as encoding properties in the structure, but since anyway we can't encode all of them, who cares? At least we "color" the validated structure, and even if we use only parts of it, they would also be "colored" and we would know they passed validation -> because only the validation function can "color" stuff.
Therefore I created this PR, with `data Valid` that serves as this marker/color.
The problem however, that I wasn't aware at that point, is that I still have this problem where structure is "mutable", in the sense that invalid copies of it can be made on the fly -> this is because `data Valid` is Functor, and while I needed that to allow accessing parts of it while still keeping them colored, I forgot that if something is Functor you can basically put anything in it (`(\_ -> "Foo") <$> someFunctor` will put "Foo" into functor regardless of what is already in it). Which means you could easily "color"/"mark" anything if you had even one instance of "colored" value. And that kind of ruins the whole thing! Again, solution is allowing only predefined getters, so we are sure it is a piece of existing structure that is being returned, but that would again require quite some boilerplate. And as you can see in the code, dealing with `Valid` and moving stuff out of it or manipulating them while inside of it is already complicated enough, so I at the very end concluded this is also just too complex at the time being.

I will leave this PR often for a bit still, just so you can see what it took to implement this, as I used some fun things for the first time (`pattern synnonims` language extension). 

I wonder also if Lenses could somehow play into the whole thing, since they have the notion of Getter, but I haven't investigated that enough.

Conclusion: Real solution would need to do coloring OR use new IR, AND also make sure that only getters are available. In both cases, that is a lot of work and duplication, and I concluded it is best to skip it for now and go with the simplest solution, which you can see in another PR: https://github.com/wasp-lang/wasp/pull/459

### CODE REVIEW

**Comment by shayneczyzewski** [comment]
Great writeup and strongly-typed attempt, @Martinsos! I have not used pattern synonyms before, so it was neat to see and learn a bit more about here: https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pattern_synonyms.html

I think you had this approach, with the pros and cons very well thought out. I agree it would be great to leverage Haskell as much as we can, either via patterns or new type wrappers, and limiting getters. The injecting or recreating "valid" invalid ones, and vice-versa, is def a problem to consider. And if you went Lenses I think my mind may melt lol.

I think for now the second approach makes the most sense to me, as it is easily extendable with more checks, and uses a now familiar error/warning mechanism. When in doubt, I prefer the simpler approach :D But agree it would be nice if in the future could have the type system enforce it, but this should be good enough to get us started. 👍🏻 

Lastly, in the TS-enforced vs convention/trust-required approach dichotomy, I think there are some aspects we want to protect against (like _accidentally_ making a valid become invalid, etc.) vs protecting against intentionally malicious users trying to usurp invariants. The TS part helps both, but I think in our case we can just try our best to add enough safeguards to prevent the former, even if we don't have the 100% guarantees to prevent the latter. :) 

Great job!!

**Comment by faassen** [comment]
I just wanted to drop in a note that "Domain Modeling Made Functional" makes much of using types to help ensuring valid data, so it's neat to see you use the pattern of moving from an invalid app spec to a ValidAppSpec here too. AppSpec is, after all, a domain model of sorts. And validation at the boundary is indeed very important; you can get rid of a lot of defensive code that checks whether things are there if you do so.

**Comment by faassen** [comment]
> If a Page has authRequired set, then app.auth also needs to be defined.

> I think we could store the info about Pages that have authRequired into app.auth, and that way would ensure that property, but 
> that would make it a bit impractical to deal with specific pages, since we would have to do lookup in the app.auth.

Thinking about this, I guess there are two aspects of this:

* We don't want to see a page that says auth required if the app doesn't define auth

* We don't want to see an app without auth if there is any page that requires auth

I think your answer focuses on the second approach. The first would refuse to create a AuthRequiredPage unless the app defines the auth details. If any such page cannot be created, the whole process fails anyway. The problem remains that the App then has a maybe auth and the AuthRequiredPage still needs to check on it. I wonder whether the answer here isn't a form of normalization instead of validation - if an auth is missing we construct auth that always fails to authenticate. That way we can rely on the auth to always be there in the ValidatedApp. If we combine that with refusing to build a ValidatedAuthPage without there being an auth in the original app spec, we'd gain at least some of the benefits of the type system.

**Comment by faassen** [comment]
quoting Shayne (it took me a while to read 'TS' not as typescript but type system):

> Lastly, in the TS-enforced vs convention/trust-required approach dichotomy, I think there are some aspects we want to protect > against (like accidentally making a valid become invalid, etc.) vs protecting against intentionally sneaky devs trying to usurp
> invariants (how the functor example partially came across).

I agree with that: the type system is there to help developers avoid accidental mistakes. Deliberate corruptions of the system aren't a thing we shouldn't worry about with the type system. Avoiding accidental mistakes is good enough. The debate about 'private/protected/public' in OO languages is similar: is this to help developers to protect invariants in the code or is it a security measure? In C++ it can't really be a security measure as I could do all kinds of low level stuff to get around it. It can still be useful.

**Comment by Martinsos** [comment]
Thanks for comments!

I have to admit I wasn't thinking much about protecting from user input, I was merely focusing on avoiding developer mistakes. But as you both said, both can be covered with parsing/validation.

Quote by Martijn:

> validation at the boundary is indeed very important; you can get rid of a lot of defensive code that checks whether things are there if you do so

This quote very well describes my intentions! And comes down to what is described here https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/ .

Hmmmm, so your idea @faassen is to provide "default auth" when there is no auth, in the sense that "default auth" is auth that does not work really. Interesting direction but that seems to me like it pulls other problems with it -> how are we dealing with this down the line? But I think to reason about this concretely, you really need to have an idea of how it is used and what "auth" actually means, stands for. With my current knowledge I can hardly imagine this direction ending up practical, but it might be also that I am not fully in grasp of this solution hm.

Let's see what we come up with in the future!

**Comment by matijaSos** [comment]
Just to chime so you can see I also read the discussion! :D All makes sense to me, especially liked how @shayneczyzewski 
 and @faassen explicitly delineated between "accident" vs "sneaky action attempt" by developers -> I agree that the first one is the priority, if we manage to do that it would already be great :). I think it's great we are going with the simpler solution for now but are aware of the cost/shortcomings -> then when we become smarter in the future we'll be able to improve it in the right way :). In short, it's better to have a well-understood problem than the not-really-sure-about solution :D.

**Comment by Martinsos** [comment]
Thanks for the wise words @matijaSos :D!
Closing this one then.

**Pull request closed without merging**
