### PR TITLE
E2e tests accepting

### PR DESCRIPTION
**Pull request by Martinsos**
Added short instructions to README about e2e tests, focused on how to accept that changes in the generated code.

Also added convenient command to `./run` script for accepting the e2e changes.

### CODE REVIEW

**Comment by Martinsos** [comment]
I accidentaly had a piece of README changes get into earlier PR where I was updating Prisma so that already got into `main`, that is the reason why here the e2e section in README is only modified instead of created.

**Review by shayneczyzewski — APPROVED** [review]
This is great, thanks for beating me to this @Martinsos! 😅 The doc updates are great and this is a very handy helper to speed up running e2e. Nice job!

**Comment by Martinsos** [comment]
Awesome thanks @shayneczyzewski ! Ha you did all the hard work, I merely wrote what you previously explained in Discord, but this is mostly for me because I forget every time how to do it. Btw I wonder if anybody else uses that ./run script except me - I actually find it very useful! And I keep promoting it :D

**Comment by shayneczyzewski** [comment]
Haha love the `run` script promotion @Martinsos , I do actually use it too! 🤖

**Pull request merged**
