### PR TITLE
Cycle Install Progress messages

### PR DESCRIPTION
**Pull request by santolucito**
### Description

> Describe your PR! If it fixes specific issue, mention it with "Fixes # (issue)".

Cycle install progress messages. This makes it a bit easier to see progress once your terminal is full. Also a bit more fun then just printing the same message after a while.

### Select what type of change this PR introduces:
1. [x] **Just code/docs improvement** (no functional change).
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [ ] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### Update example apps if needed
If you did code changes and added a new feature or modified an existing feature, make sure you satisfy the following:
1. [ ] I updated `waspc/examples/todoApp` as needed (updated modified feature or added new feature) and manually checked it works correctly.
2. [ ] I updated `waspc/headless-test/examples/todoApp` and its e2e tests as needed (updated modified feature and its tests or added new feature and new tests for it).

### CODE REVIEW

**Comment by sodic** [comment]
Hey @santolucito, thanks for the contribution!

Cool stuff, I tried it out and it works. The code is cleaner too, and serves as a nice demo of Haskell's laziness.

I'll merge it as soon as you take care of failing CI/CD.

**Comment by santolucito** [comment]
ah just saw the CI. Looks like I need to fix my formatter config. My ormolu install wants to rewrite some imports as such:

```
- import qualified Data.Text as T
+ import Data.Text qualified as T
```

Is the ormolu config that is used for this project documented somewhere? I am using the [Haskell VSCode extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell), but this seems to be doing something different than what this project uses (for imports at least).

**Comment by sodic** [comment]
@santolucito What happens when you run `./run ormolu:format` as described here? https://github.com/wasp-lang/wasp/tree/main/waspc#run-script.

I should add the formatting point to the contributor steps.

**Comment by santolucito** [comment]
I fixed the formatting with the above commit. It seems that you all are using an older version of ormolu than I had by default - I think due to https://github.com/wasp-lang/wasp/blob/5e8dbf798f718cfa4012eb71c2cbe8bfe078e061/waspc/dev-tool.project#L9. This seems to be something others ran into as well: https://github.com/tweag/ormolu/issues/1010

I was able to get my VScode ormolu version to match this project's by adding the below to my settings.json in vscode. I am honestly not sure if this is what actually fixed, but now it seems to be working anyway.

```
    "haskell.toolchain": {
        "ormolu": "0.5.1.0",
    }
    
```

**Comment by sodic** [comment]
@santolucito Ok, merged! Thanks again.

> I fixed the formatting with the above commit. It seems that you all are using an older version of ormolu than I had by default

Hm, possible. That's why we rely on running `./run ormolu:format` from the command line. That way, it should read the project's settings in `dev-tool.project`.

Can you confirm this behaves as expected? If not, I should address it :smile:

**Comment by santolucito** [comment]
Yes, that worked as expected. I'll do that from now on!

**Comment by santolucito** [comment]
Thanks for the merge as well!

**Pull request merged**
