### PR TITLE
Fixed how we do caching in GA.

### PR DESCRIPTION
**Pull request by Martinsos**
Cache was not being updated after each run, which is not the behaviour we want for haskell/stack -> we want it to be used and then updated on each run. More details in the comments in the code.

I also replaced $HOME with ~ because I saw they use ~ in all the examples + I noticed our cache was 0MB so it is possible that $HOME was not working as it should (not sure).

### CODE REVIEW

**Comment by Martinsos** [comment]
@drkameleon please give it a look!

**Comment by drkameleon** [comment]
> @drkameleon please give it a look!

I was also a bit in doubt what was going on with the cache. I had never bothered with it in the past tbh, but given how much time rebuilding it all from zero (stack, haskell and the dependencies), it sure makes a lot of sense.

Let's see how the run goes. I'll look into it.

**Comment by Martinsos** [comment]
Ok great! With stack it makes a huge difference, from 20 minutes to 2 minutes, due to how long it takes to build these external dependencies.
You don't have to look into anything special, I just wanted to include you in case you find it useful.

**Comment by drkameleon** [comment]
> With stack it makes a huge difference, from 20 minutes to 2 minutes, due to how long it takes to build these external dependencies.

I know... The first time I built Wasp from sources here, I was wondering what was going on. (Imagine that I'm used to installing Nim and everything, in less than 30 seconds)

**Comment by Martinsos** [comment]
Ok, builds now take just a couple of minutes! Except for Windows, we can make that work in separate PR.

I encountered interesting problem with on MacOS -> there is a bug it seems, where cached executables don't work. I resolved it by just deleting that executable from the cache, as a temporary fix.

I will merge this one so we get the benefits of faster builds!

**Pull request merged**
