### PR TITLE
Remove rudandant aboslute API URLs

### PR DESCRIPTION
**Pull request by sodic**
I've noticed this while reviewing #749 . Specifying the `baseURL` twice (once in the global config and the other time in each API call) leads to weird/inconsistent behaivor.

For example, setting `REACT_APP_API_URL` to the string `"something"` and doing `api.get(config.apiUrl + '/auth/me')` performs a call to `http://localhost:3001/something/something/auth/me`. You can read [Axios's docs](https://axios-http.com/docs/req_config) if you want to know why.

### CODE REVIEW

**Review by Martinsos — APPROVED** [review]
Good one, this is a bug, I must have left this by accident!I actually wonder why it worked well, maybe because we used `/` for baseUrl?

**Review by shayneczyzewski — APPROVED** [review]
Great find @sodic! The `api` calls now look a lot cleaner, too.

One additional place we can probably remove it is something I did following this existing convention: https://github.com/wasp-lang/wasp/blob/6cd38b0f942529d641b59b79eed49b4193df70c8/waspc/data/Generator/templates/react-app/src/auth/pages/OAuthCodeExchange.js#L33

Although the Google OAuth stuff is a pain to setup, so I can test it out today and let you know if it works as expected (it should) if you want to include that. If not, no sweat, I can update it later 👍🏻

**Comment by sodic** [comment]
> Great find @sodic! The `api` calls now look a lot cleaner, too.
> 
> One additional place we can probably remove it is something I did following this existing convention:
> 
> https://github.com/wasp-lang/wasp/blob/6cd38b0f942529d641b59b79eed49b4193df70c8/waspc/data/Generator/templates/react-app/src/auth/pages/OAuthCodeExchange.js#L33
> 
> Although the Google OAuth stuff is a pain to setup, so I can test it out today and let you know if it works as expected (it should) if you want to include that. If not, no sweat, I can update it later 👍🏻

Haha, yeah, I left this one in in purpose for two reasons:
- I couldn't easily test it out
- It is constructed in a place that's different from the API call site and that function technically shouldn't know about how it's being used
- 
Therefore, I think it's fine (even perhaps better) if we left it as is - absolute path will override the config anyway, and we'll reduce our chances of breaking it in the future (e.g., if we ever change our authentication workflow to include a different server).

**Comment by shayneczyzewski** [comment]
> 

Good point! Ok, let's leave as-is then. LGTM nice work here! 🚀

**Pull request merged**
