### PR TITLE
Get set up to run stan for static analysis

### LINKED ISSUE #363: Stan found 253 observations.
Please review and address the observations of [stan](https://github.com/kowainik/stan).

[stan.html.zip](https://github.com/wasp-lang/wasp/files/7532341/stan.html.zip)

```
> cabal install stan
waspc> stan report

           Stan's Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ Analysed modules             ┃ 152    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Analysed Lines of Code       ┃ 9550   ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total Haskell2010 extensions ┃ 19     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total SafeHaskell extensions ┃ 0      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total checked inspections    ┃ 44     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total found observations     ┃ 253    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total ignored observations   ┃ 0      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Project health               ┃ 61.36% ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━┛

  ⓘ Report is generated here -> stan.html
```

### PR DESCRIPTION
**Pull request by philderbeast**
# Description

Prepares the project for static analysis with stan but does not fix any of the observations stan reports.

Fixes #363, partially.

* Adds a static analysis section in the readme for waspc.
* Adds options in the cabal file to generate hie files in the place that stan expects them to be by default.
* Ignores the generated hie files.

## Type of change

Please select the option(s) that is more relevant.

- [x] Code cleanup
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Martinsos** [comment]
Great, thanks for doing this!

I left just a couple of small suggestions, let's take care of those and I will merge, and then we can look into fixing the observations and possibly even enabling stan in the CI.

Btw how would you explain the difference between stan and hlint? I read the short piece about it they have in stan's README, and while it explains the workings of stan vs hlint, and that they have different goals, it doesn't explain how are those goals different.

**Comment by Martinsos** [comment]
Oh, and we should also consider adding Wasp to the list of companies using Stan, at the bottom of their README!

**Comment by philderbeast** [comment]
> Btw how would you explain the difference between stan and hlint?

"In short, the tools are completely different, use different approaches and provide different types of analysis."   
SOURCE: https://twitter.com/ChShersh/status/1275061973898506245

**Comment by Martinsos** [comment]
@philderbeast love what you did with the stack-stan.yaml! This is great, it gives us a way to easily install `stan` that we use just for this project, locally. I wasn't aware of `local-bin` option, that is great.

Just to clarify - I see `stan` isn't on Stackage. So how does this work then? `stack` doesn't care and will pull it from hackage but then we have to specify all the dependencies that are also not on Stackage? How does it know which version of `stan` to install? I guess the newest one, since that is not specified? What is important here, I guess, is that we have resolver specified, so Stack will use specific GHC defined by that resolver for compiling `stan` and its dependencies?

Does it at the end come down to the same thing as if we used `cabal install stan -w ghc-8.10.1` - why not use that then? Because it has no `local-bin-path` option, and we would have to figure out version of ghc based on the resolver?

What about https://www.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots/ -> would this enable us avoid duplication of the `resolver`, by having both `stack.yaml` and `stack-stan.yaml` use `snapshot.yaml` where we extract `resolver`?

**Comment by Martinsos** [comment]
> > Btw how would you explain the difference between stan and hlint?
> 
> "In short, the tools are completely different, use different approaches and provide different types of analysis." SOURCE: https://twitter.com/ChShersh/status/1275061973898506245

Yeah, but it comes down to them explaining that Stan is more powerful because it uses HIE. They don't explain what is the difference between the goals -> as far as I can see, Stan could also do the things that hlint does, the main reason it wouldn't do so is because hlint is already doing them. It's not super important, I am ok with using both, I was just curious if there is explanation beyond "stan does what hlint can't but it won't do what hlint currently does since hlint already does it".

**Comment by philderbeast** [comment]
> Does it at the end come down to the same thing as if we used `cabal install stan -w ghc-8.10.1` - why not use that then? Because it has no `local-bin-path` option, and we would have to figure out version of ghc based on the resolver?

To do the same thing with cabal, to build stan with `ghc-8.10.7` and then install to `.bin/stan`:
```
> cabal install stan -w ghc-8.10.7 --installdir=.bin --install-method=copy --overwrite-policy=always
Resolving dependencies...
Up to date
Copying 'stan' to '.bin/stan'
```

**Comment by Martinsos** [comment]
> > Does it at the end come down to the same thing as if we used `cabal install stan -w ghc-8.10.1` - why not use that then? Because it has no `local-bin-path` option, and we would have to figure out version of ghc based on the resolver?
> 
> To do the same thing with cabal, to build stan with `ghc-8.10.7` and then install to `.bin/stan`:
> 
> ```
> > cabal install stan -w ghc-8.10.7 --installdir=.bin --install-method=copy --overwrite-policy=always
> Resolving dependencies...
> Up to date
> Copying 'stan' to '.bin/stan'
> ```

Awesome, thanks for this!

**Comment by philderbeast** [comment]
> Just to clarify - I see `stan` isn't on Stackage. So how does this work then? `stack` doesn't care and will pull it from hackage but then we have to specify all the dependencies that are also not on Stackage? How does it know which version of `stan` to install? I guess the newest one, since that is not specified? What is important here, I guess, is that we have resolver specified, so Stack will use specific GHC defined by that resolver for compiling `stan` and its dependencies?

Yes stack is pulling the latest version from hackage, same as if I'm browsing to the latest version implicitly or explicitly.

https://hackage.haskell.org/package/stan
https://hackage.haskell.org/package/stan-0.0.1.0

In `extra-deps` I'm listing the dependencies not in the stackage snapshot (or at the wrong version there) and stack pompts me what to use. For instance if `extra-deps` is empty then I get this response from stack:

```
> stack install stan --stack-yaml=stack-stan.yaml

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for stan-0.0.1.0:
    colourista must match ^>=0.1.0.0, but the stack configuration has no specified version  (latest matching version is 0.1.0.1)
    dir-traverse must match ^>=0.2.2.2, but the stack configuration has no specified version  (latest matching version is 0.2.3.0)
    extensions must match ^>=0.0.0.1, but the stack configuration has no specified version  (latest matching version is 0.0.0.1)
    microaeson must match ^>=0.1.0.0, but the stack configuration has no specified version  (latest matching version is 0.1.0.0)
    optparse-applicative-0.16.1.0 from stack configuration does not match ^>=0.15  (latest matching version is 0.15.1.0)
    pretty-simple-4.0.0.0 from stack configuration does not match ^>=3.2  (latest matching version is 3.2.3.0)
    slist-0.2.0.0 from stack configuration does not match ^>=0.1  (latest matching version is 0.1.1.0)
    trial must match ^>=0.0.0.0, but the stack configuration has no specified version  (latest matching version is 0.0.0.0)
    trial-optparse-applicative must match ^>=0.0.0.0, but the stack configuration has no specified version  (latest matching version
                               is 0.0.0.0)
    trial-tomland must match ^>=0.0.0.0, but the stack configuration has no specified version  (latest matching version is 0.0.0.0)
needed since stan is a build target.

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps in /.../stack-stan.yaml:

- colourista-0.1.0.1@sha256:98353ee0e2f5d97d2148513f084c1cd37dfda03e48aa9dd7a017c9d9c0ba710e,3307
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
- extensions-0.0.0.1@sha256:16517ab9df3dd6c7a20da746c8ed02cfd59c8cb40ae5719aef8b5dd4edceadc0,3993
- microaeson-0.1.0.0@sha256:ddb1bfa843b3de5e105485b4ecd362ca7d0ccabb19901dd7786846caccf42d67,3456
- optparse-applicative-0.15.1.0@sha256:29ff6146aabf54d46c4c8788e8d1eadaea27c94f6d360c690c5f6c93dac4b07e,4810
- pretty-simple-3.2.3.0@sha256:7d054c500d2918e6c7723f29b9d212d27359dbd231d7eeca1900d60042e9a16f,4137
- slist-0.1.1.0@sha256:4896d54f16493697facb4b2a23395d95de5eefe2a0e9acdb62d8bb034846070d,2537
- trial-0.0.0.0@sha256:834d3be439dc9b52a759a45a4d3944e5e55c3d50fd5874003147cc1f6231d4aa,4301
- trial-optparse-applicative-0.0.0.0@sha256:ba05edfc327a281766df5e0f44d91229e6a98afaf59abe1894b293453f076192,2449
- trial-tomland-0.0.0.0@sha256:743a9baaa36891ed3a44618fdfd5bc4ed9afc39cf9b9fa23ea1b96f3787f5ec0,2526

Plan construction failed.
```

**Review by Martinsos — APPROVED** [review]

**Pull request merged**
