### PR TITLE
Improved the Security Contact Information

### PR DESCRIPTION
**Pull request by tvermaashutosh**
### Description

Enhanced/improved the Security Report Guidelines as well as the Security Contact Information via updating the SECURITY.md file. Making it more clear/comprehensible for the users.
**Closes:** #1547 

### Select what type of change this PR introduces:

1. [x] **Just code/docs improvement** (no functional change). 
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [ ] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### CODE REVIEW

**Comment by tvermaashutosh** [comment]
@Martinsos @sodic 
Please review my PR and if according to the guidelines please do merge it :)

**Comment by tvermaashutosh** [comment]
@Martinsos @sodic 
Have you reviewed my PR? Are there any changes to be made?

**Comment by tvermaashutosh** [comment]
Closes Issue: #1547

**Comment by Martinsos** [comment]
@tvermaashutosh thanks for the effort here!
Unfortunately, this is not the change we can accept at this moment. This updated security doc make quite a bit of claims and promises that we haven't had the opportunity yet to think through and/or decide to stick with them; for some of them we also currently don't have the resources.
Wasp is still in Beta, so I would rather we keep our security processes quite simple at the moment, and we can evolve them as time goes. Once we come to 1.0, this will be worth revising and taking to the next level, but for now I would rather keep it quite simple and agile.

**Pull request closed without merging**
