### PR TITLE
Get `npm install` during `wasp start` to output more details

### PR DESCRIPTION
**Pull request by turbodami**
# Description

First possible solution suggested in the issue is excluded as there are no flags to be passed to `npm install`
Trying second solution, use script to cheat `npm install` into thinking it is being run interactively (like prisma commands do), doesn't seem to output more details as well.

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Martinsos** [comment]
Hm, I expected this to help! Any idea why it doesn't work? Is it possible that `npm install` is so smart it can figure out it is being called by `script`?

Some ideas:
- Have you tried running it via `script` manually, to see if that works?
- What does the internet say -> had other people tried to run it via `script` and failed/succeded?
- Have you run `wasp clean` before you tested out which output `npm install` prints, to ensure it is actually installing stuff?

**Comment by turbodami** [comment]
I found [this](https://github.com/npm/npm/pull/15914), maybe `--json` or `--parseable` could do the trick. Trying all of those tomorrow.

**Comment by Martinsos** [comment]
> I found [this](https://github.com/npm/npm/pull/15914), maybe `--json` or `--parseable` could do the trick. Trying all of those tomorrow.

Hm maybe, but keep in mind we want to get the output while the installation is happening, not at the very end when installation is done. It is all about showing progress to the user. I am not sure but I am suspecting `--json` or `--parseable` might provide output only when `npm install` is done.

What about the approaches I described above, trying to get it to work with `script` - have you tried those? I am still surprised those don't work.

**Comment by Martinsos** [comment]
Closing this one and hoping that there will be a new attempt in the future!

**Pull request closed without merging**
