### PR TITLE
docs: updating v0.13 references in docs to 0.14

### PR DESCRIPTION
**Pull request by LLxD**
### Description
A small documentation fix was found while writing about Wasp's GitHub OAuth. The doc still references the v0.13 version, instead of the new v0.14.

### Select what type of change this PR introduces:
1. [X] **Just code/docs improvement** (no functional change).
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [ ] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### Update example apps if needed
If you did code changes and added a new feature or modified an existing feature, make sure you satisfy the following:
1. [ ] I updated `waspc/examples/todoApp` as needed (updated modified feature or added new feature) and manually checked it works correctly.
2. [ ] I updated `waspc/headless-test/examples/todoApp` and its e2e tests as needed (updated modified feature and its tests or added new feature and new tests for it).

### CODE REVIEW

**Comment by LLxD** [comment]
Oh, noticed that there are actually a bunch of instances where `^0.13.0` is referenced. The idea is to maintain that?

**Comment by sodic** [comment]
> The idea is to maintain that?

@LLxD Definitely not. This is a mistake, nice catch!

@infomiho What do we do about this? I can ask @LLxD to replace all occurrences of the wrong version (or we could do it), but we run into the same problem when we release the next version.

Do we just keep updating it manually?

I think we should either implement a CI/CD check for this or remove Wasp version mentions from the code snippets.

**Review by sodic — APPROVED** [review]

**Comment by sodic** [comment]
I'll merge this for now and later revisit my question from above.

**Review by sodic — COMMENTED** [review]
@LLxD Can you take care of the other 0.13.0 strings in the docs before I merge. We'd like to get all of them :)

**Comment by LLxD** [comment]
Hey @sodic! Thanks for the response!

I did a search and replace with the ones I think the change made sense, could you do a quick revision? Tried to separate them into some different commits
- One for auth related
- One for versioned ^0.14.0 versioned (which strangely had 0.13 references in them too)
- One for the rest of the files that referenced (a few files are missing, like 0.13.0 versioned of migration files, though)

So in general, just an overview may suffice here ;D

Thanks!

**Comment by sodic** [comment]
Hey @LLxD, thanks a lot!

This looks good to me, and I appreciate the thoroughness.

Btw, no need to spend so much time separating commits for future contributions, we squash them anyway :)

**Pull request merged**
