### PR TITLE
Prettier config

### PR DESCRIPTION
**Pull request by martinovicdev**
### Description

PR in relation to issue #1489. I have introduced .prettierrc file instead of prettier.config.js due to extension not working properly with the .js file. .prettierignore file has the exceptions for things such as Markdown files, static folder and .docusaurus folder. 

### Select what type of change this PR introduces:

1. [x] **Just code/docs improvement** (no functional change). 
2. [ ] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [ ] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### CODE REVIEW

**Comment by Martinsos** [comment]
Nice one @martinovicdev ! Sorry for taking a bit to take a look at this one, I will not be more responsive.

Nice that we are going to have prettier now, that is great!
I guess you had to make it work with docusaurus so that is that plugin for -> makes sense.

What could be cool is if we also added prettier to pre-commit hooks. I did it for another project couple of days ago, by following instructions in prettier's docs, it was quite easy -> but maybe it would be harder here due to docusaurus? It used stuff like `husky` and `lint-stage`. If this is interesting, maybe we could add it to this PR? Or we can leave it for later.
Oh and if we are doing this I would also add a command for formatting everything, something like `npm run format` that will really just do `prettier . --write`, so that even folks who don't have prettier set up in their editor can contribute.

**Comment by martinovicdev** [comment]
I suggest rebasing and adding `npm run format` to the code for now. I am open to making precommit hooks in a separate PR, as they are a new thing that we're adding in the workflow.

**Comment by Martinsos** [comment]
I see you did some changes but it has redundant commits and is still in conflict -> let me know if any help is needed!

**Comment by Martinsos** [comment]
Awesome @martinovicdev , this is looking good, merging! Thanks!

**Pull request merged**
