### PR TITLE
Added a note on upgrading to the latest LTE for WSL and Ubuntu users

### PR DESCRIPTION
**Pull request by EmmanuelTheCoder**
Added a note inside the docs for WSL and Ubuntu users in order to avoid the `glibc_2.34` not found error when trying to run Wasp 0.7.1. This is in relation to issue #867.

### CODE REVIEW

**Comment by Martinsos** [comment]
Thanks @EmmanuelTheCoder ! This problem can also happen for Ubuntu users, so we should also put a NOTE for them?

Suggestion:
- let's put NOTE both for linux and for wsl
- let's make note shorter and a bit more generic, so we don't have to maintain it, smth like "NOTE: If you are getting glibc errors, likely solution is to upgrade your linux version. Check (link to issue) for more details."

**Comment by EmmanuelTheCoder** [comment]
I am aware that this problem can also happen to Ubuntu users but putting "note for linux and wsl" in the docs will be a little confusing as Ubuntu is not the only Linux distro and we are not sure if this problem happens to users on other distros. 

I think a better way will be "Note for Ubuntu and WSL." Let me know your thoughts on this before amending the pull request @Martinsos .

I agree that we should make the note shorter and then point to the issue of GH in case anyone wants to read more about it.

**Comment by Martinsos** [comment]
@EmmanuelTheCoder sorry for slow response on this one!
I think it can happen on any distro hm. Maybe we should just have a super short note like "getting glibc errors? Check here: <link to gh issue>".

I see you closed the PR, what happened?

**Comment by EmmanuelTheCoder** [comment]
The main reason why I closed this was that I discovered I didn't create a branch for this, twas pushed to main. I will create another PR for this.

Which is better:
a. showing them how to solve the glibc error in docs in a few lines and then linking back here in case they want to read more.
b. making a super short note, "getting glibc errors? check here" that links here.

In my opinion, I think option a is better for good DevEx. 
@Martinsos

**Comment by EmmanuelTheCoder** [comment]
Or what do you think?

cc @vincanger

**Comment by Martinsos** [comment]
I am voting for b) due to it being easier to maintain for us + it will draw less of their attention from the docs, where there is already a lot of info.

**Comment by EmmanuelTheCoder** [comment]
@Martinsos, made a pull request for this #895. Kept it super short as suggested.

**Pull request closed without merging**
