### PR TITLE
fix: flag when new project name is a reserved word.

### LINKED ISSUE #354: `wasp new` accepts reserved word "app"
Working through the tutorial I found a name accepted by `wasp new` but rejected by `wasp start`.

https://github.com/wasp-lang/wasp/blob/a9aa4ff446bdd1b81bf76a8192a9202b4d4ffa97/web/docs/getting-started.md?plain=1#L102

```diff
-- wasp new MyNewApp
++ wasp new app
```

```
> wasp new app
Created new Wasp app in ./app directory!
To run it, do:

    cd app
    wasp start

NOTE: Wasp is still in Alpha, therefore not yet production ready and
might change significantly in the future versions.
> cd app
> wasp start
Compiling wasp code...
Error: Compilation failed: (line 1, column 8):
unexpected reserved word "app"
expecting letter or digit or "_"
```

### PR DESCRIPTION
**Pull request by Martinsos**
fixes #354.

### CODE REVIEW

**Comment by philderbeast** [comment]
@Martinsos I'm getting a similar error locally when building the master branch as the CI run does here for this PR for `macos-latest` .

```
# local error

Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/wasp/wasp ...
ld: can't write output file to '.stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/wasp/wasp' because that path is a directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
Progress 1/2

--  While building package waspc-0.2.2.2 (scroll up to its section to see the error) using:
      /.../.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:waspc exe:wasp test:waspc-test --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

```
# ci error

Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/wasp/wasp ...
ld: can't open output file for writing: .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/wasp/wasp, errno=21
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package waspc-0.2.2.2 (scroll up to its section to see the error) using:
      /Users/runner/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:waspc exe:wasp test:waspc-test --ghc-options ""
    Process exited with code: ExitFailure 1
Error: Process completed with exit code 1.
```

**Comment by Martinsos** [comment]
Hey @philderbeast thanks for helping with this, I just noticed! I restarted CI build, but if you are getting this locally, then it will probably also happen again on CI.

I am wondering if this is caused by the refactoring that I introduced, where I moved all the code one level deeper into Wasp/ dir.

Could you try cleaning your stack cache with `stack clean` and then re-running `stack test`? If that helps, I will clean the CI cache and that should solve the problem then.

**Comment by philderbeast** [comment]
If I rename `wasp` -> `wasp-exe` for the exe in `package.yaml` then I don't hit the problem. Could it be case insensitivity at play?

Screen Shot 2021-11-11 at 11 13 49 AM

**Comment by Martinsos** [comment]
@philderbeast might be, although I would be surprised -> it might also be that you just avoided the cache that way. What happens if you do `stack clean`?

I will go and clean the CI cache -> it is taking a bit because they have no UI for that so I have to manually modify the workflow yaml file to achieve this, but I should have it happening soon.

**Comment by philderbeast** [comment]
Happens when I delete `.stack-work` and when I `stack clean` before `stack build waspc:wasp`. No problem with `cabal build waspc:exe:wasp`.

**Comment by Martinsos** [comment]
> Happens when I delete `.stack-work` and when I `stack clean` before `stack build waspc:wasp`. No problem with `cabal build waspc:exe:wasp`.

Uff that is not great, I was really hoping `stack clean` would take care of it.
I will let the CI finish to see how that goes now that I told it to use new cache, and will then dig down into it.

**Comment by Martinsos** [comment]
Ok, I also confirmed with @matijaSos that it is same for him on MacOS - it doesn't build even if he deletes .stack-work or does `stack clean`. So this has nothing to do with old cache.

Also, problem happens only on Mac.

The biggest change I did was refactor all the code so that all modules are in Wasp module as top module, so I am thinking it must have to do with that. On the other hand, you fixed it by renaming executable to wasp-exe. All this makes it sound like there is some conflict between the name of the executable and the name of the top module in library, which sounds silly but it is too related to be a coincidence.

I will try to replicate this with a simpler project and will file a bug on Stack.

In the meantime I will also rename our exe but then I need to make sure to also update the installer script so it correctly installs the executable and there might be other places where I need to update something -> I would rather avoid it.

**Comment by Martinsos** [comment]
I brought it down to this simple example: https://github.com/wasp-lang/wasp/tree/mac-build-error/waspc .

**Comment by Martinsos** [comment]
I opened issue at stack repo: https://github.com/commercialhaskell/stack/issues/5636 .

**Comment by Martinsos** [comment]
I also renamed executable as a workaround -> thanks @philderbeast for that idea! https://github.com/wasp-lang/wasp/pull/360 .

I will merge this one in the meantime since it passes on Ubuntu.

**Pull request merged**
