### PR TITLE
Fix unresponsive UI on server reload

### LINKED ISSUE #620: UI becomes unresponsive after server reload from code change
**Describe the bug**
@sodic mentioned in Discord that the browser UI would become unresponsive, mouse stays an arrow permanently, and no clickable elements would be clickable after making a code change to project files and the server reloaded. Can reproduce 100% of the time.

I was able to reproduce too, and tried to bisect it down to find the offending commit, which was: https://github.com/wasp-lang/wasp/commit/8bc004ef29b2af9fecf564ae8e7248d0d3dcd708

In this commit, @Martinsos and I tried to make Wasp smarter by writing fewer files to disk as part of the generation process (aka write only the subset of files that differed from those on disk). Clearly, this process is not playing nicely with the browser and/or tooling (like nodemon).

One clue is in the browser we get the following console error when this happens:

```js
VM164:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1:1)
```

**To Reproduce**
1. Start any app with a version after this change
2. Make a change to a project file
3. See browser become unresponsive
4. Refresh to "fix"

Happens across Linux, Windows, and Mac.

### PR DESCRIPTION
**Pull request by shayneczyzewski**
# Description

Fixes an unresponsive UI on reload as a result of a breaking change in `react-error-overlay` used by `react-scripts` v4. Some links for reference:
- https://bobbyhadz.com/blog/react-referenceerror-process-not-defined
- https://github.com/facebook/create-react-app/issues/11773
- https://charles-stover.medium.com/resolving-create-react-apps-uncaught-referenceerror-process-is-not-defined-63f12a069b03
- https://github.com/facebook/create-react-app/issues/11771

Fixes #620

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by sodic — APPROVED** [review]
I went through the links in the issue description, and this does seem to be the appropriate fix. Any ideas on how we can make sure to remove this fix once react-scripts comes up with an official solution?

Great job digging this up!

**Comment by shayneczyzewski** [comment]
We could also consider upgrading `react-scripts` to v5 sometime in future too, but that may be more than a one liner.

**Comment by Martinsos** [comment]
Great find and fix @shayneczyzewski and @sodic !

One thing is that CRA (Create React App) follows this strategy of putting everything into `deps` instead of `devDeps` due to specific reasons they explain on their repo, so I would probably try to stay consistent and also add this new dependency under the `deps` instead of `devDeps`. But it doesn't really matter in practice.

**Comment by Martinsos** [comment]
I guess we could reorganize stuff, but then we would also need to put their things under dev deps, right? That is why so far I concluded it is easiest to stick with what they said, which is just put everything under dependencies. Because in theory, they are correct, everything is dev dependency when building a frontend app. I am not sure why they put it all under dependency then and not dev dependency though :D, but it makes sense to at least be consistent.
So I would just put it under dependency there? Or if you want to reorganize, I am good with that, but I think it will be hard to do it in clear manner.

**Comment by shayneczyzewski** [comment]
Sure, np, I can put it under dependency and add a comment to not use
devDependencies. Will make a PR real fast.

**Comment by shayneczyzewski** [comment]
FYI: https://github.com/wasp-lang/wasp/pull/626 Thanks!

**Pull request merged**
