### PR TITLE
Remove trailing slash, if present in the wasp backend URL

### LINKED ISSUE #332: When building the client for deployment, API requests are invalid if wasp dev puts `/` at the end of the backend server URL
In [Deploying web client (frontend)](https://wasp-lang.dev/docs/deploying#deploy-to-a-heroku-app) step, if dev puts a trailing `/` at the end of the url to the backend server, the API calls will be invalid, since it will have an extra `/` in it (e.g. `https://waspello.heroku.app//auth/me`).

It happened to me while deploying Waspello - we should either warn in the docs against it, or make the system (build script I guess?) robust to it.

### PR DESCRIPTION
**Pull request by ankeshp03**
# Description

This change adds a note in the [Deploying web client (frontend)](https://wasp-lang.dev/docs/deploying#deploy-to-a-heroku-app) step, for the devs against putting a trailing `/` at the end of the URL to the backend server.

Fixes #332 

## Type of change

Please select the option(s) that is more relevant.

- [x] This change requires a documentation update

### CODE REVIEW

**Comment by sodic** [comment]
Hey @ankeshp03,

Thanks for the PR!

I think a better fix for this would be changing the code to account for the trailing slash. Would you be interested in implementing this? If you don't have time/experience to edit the code, it definitely makes sense to update the docs before someone gets to it. I just wanted to check whether you want to do it before we merge this.

**Comment by ankeshp03** [comment]
Hi @sodic,
I can work on the code to fix it.
I updated the document instead of working on the code because the issue has `documentation` as a label, so I thought maybe we have to update the docs for now.
I will work on the code fix and raise a PR.

Thank you.

**Comment by sodic** [comment]
> I updated the document instead of working on the code because the issue has `documentation` as a label, so I thought maybe we have to update the docs for now.

Yes, the label might have been a bit underspecified :upside_down_face:. Still, editing the docs would be a perfectly valid temporary solution, but since you want to fix the code, that's even better!

**Comment by ankeshp03** [comment]
I have already fixed the code and pushed the changes.
I have also tested the fix with the `Real World App` example from the docs, and it works fine.

Please check the fix once and let me know.

Thank you.

**Comment by sodic** [comment]
Hey @ankeshp03, the change looks good, but the build is failing due to e2e tests. I'll try your code locally and merge it tomorrow. In the meantime, you can fix the e2e tests using [the procedure described in our contributors guide](https://github.com/wasp-lang/wasp/tree/main/waspc#end-to-end-e2e-tests).

**Comment by sodic** [comment]
Hey, sorry for the wait. I uncovered a bug while reviewing this that I had to fix first: https://github.com/wasp-lang/wasp/pull/755

Anyway, the fix works, we can merge it as soon as you [get the e2e tests working](https://github.com/wasp-lang/wasp/tree/main/waspc#end-to-end-e2e-tests) :).

**Comment by ankeshp03** [comment]
Hi @sodic,
No problem, I have merged with the `origin/main`.

**Comment by sodic** [comment]
Great! Only e2e tests left then and we can merge it.

**Comment by ankeshp03** [comment]
It shows workflow is awaiting approval.

**Comment by sodic** [comment]
Haha, yes, but we can be sure it will fail because e2e tests haven't been updated :)

Please the contributors guide about e2e tests I linked in my previous comments. After performing the necessary steps, and you'll see what I mean.

**Comment by ankeshp03** [comment]
Okay thanks, I will check the guide and follow the steps then.

**Comment by ankeshp03** [comment]
Hi @sodic
I have performed the e2e tests as per the guide and pushed the changes, I hope it won't fail the test now.
Please let me know if it is okay or if I have to do anything else.

Thank you.

**Comment by sodic** [comment]
Hm, that's strange, I see you generated the tests, but the hashes don't match. What do you get when you run `./run test:e2e` in `waspc`? I get 6 failures (i.e., it matches the CI/CD result). If you're getting something else, we might have a system-dependent bug.

**Comment by ankeshp03** [comment]
I guess I got what could have been the issue.
While installing the required packages and since bash is not working in my local, I might have messed up somewhere in the files.

I have fixed it, hopefully, this commit will pass the e2e tests. 🤞🏼

**Comment by sodic** [comment]
> I have fixed it, hopefully, this commit will pass the e2e tests. 🤞🏼

Sure did!

Nice work and thank you :smile:

**Pull request merged**
