### PR TITLE
Put contrasting box around blog intro / CTA part, to distinguish it visually from the content

### LINKED ISSUE #462: [Blog] Individual post - Put some contrasting box around blog intro / CTA part, to distinguish it visually from the content
Right now, it is hard to distinguish CTA from the text:

wasp_blog_post_cta

### PR DESCRIPTION
**Pull request by shahx95**
# Description

Improved the CTA bar by adding a box around it to distinguish it and added media queries to make it look clean on small screens.

Screen recording gif demonstrating changes made

Fixes #462

## Type of change

Please select the option(s) that is more relevant.

- [x] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by shahx95** [comment]
@maksim36ua would you be able to review it please and provide feedback?

**Review by sodic — APPROVED** [review]
@shahx95 Thanks for the PR!

@maksim36ua I took a look at the code and tested it - it works well! You have the final say but, as far as I'm concerned, we can merge this.

**Comment by maksim36ua** [comment]
@shahx95 sorry, for the delay. Looks good to me, thanks for the contribution! @sodic thanks for the review!

Also, @shahx95 if you'd decide to join our Discord -- please ping me in DMs. Got a "contributor" title for you :)

**Comment by shahx95** [comment]
Thanks, guys!

**Pull request merged**
